apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-fastapi-app.fullname" . }}
  labels:
    app: {{ include "my-fastapi-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-fastapi-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-fastapi-app.name" . }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "my-fastapi-app.fullname" . }}
