apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-fastapi-app.fullname" . }}
  labels:
    app: {{ include "my-fastapi-app.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "my-fastapi-app.name" . }}
